# Generated by Django 3.1.5 on 2021-02-08 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_shippingaddress_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='orderitem',
        ),
    ]
